rm upload-api-proxy ability to route to separate environment audiences
web3-storage/w3protocol pull request #407
Opened 2023-01-30 22:52 UTC by gobengo

2023-01-30 23:01 UTC, gobengo commented
@hugomrdias does this fulfill what you asked for [here](https://github.com/web3-storage/w3protocol/pull/390#pullrequestreview-1275740500)?

2023-01-31 15:38 UTC, hugomrdias requested changes

2023-01-31 18:50 UTC, gobengo commented on packages/access-api/wrangler.toml
> +vars = { ENV = "staging", DEBUG = "false", DID = "did:web:staging.web3.storage", UPLOAD_API_URL = "https://staging.up.web3.storage" }
like this? https://github.com/web3-storage/w3protocol/pull/407/commits/a0f07b5c993cfb32c218bb7de78695cbeaf2836a

afaict upload-api doesn't have a 'dev' environment so I pointed it to upload-api staging

2023-01-31 20:02 UTC, gobengo commented on packages/access-api/src/bindings.d.ts
> +    ucanto?: { url: URL }
I did it here, wdyt? https://github.com/web3-storage/w3protocol/pull/407/commits/cc94badfd6f5569ad17aa9649e85d9e54bb3ea94#diff-a7cd4d05e6cba234e750cd72e2c9301b4cecec823d94002c39e928edd73b5b41L56

2023-01-31 20:02 UTC, gobengo commented on packages/access-api/src/service/upload-api-proxy.js
> +      ...uploadApi.ucanto,
I removed this default behavior by making the relevant options required and removed this function. https://github.com/web3-storage/w3protocol/pull/407/commits/cc94badfd6f5569ad17aa9649e85d9e54bb3ea94#diff-969dad085be9e4a6140a50e5f0142a0e6f106b12a5c3375f5857006fbe71dab8L74

2023-02-01 14:36 UTC, hugomrdias approved these changes
LGTM

2023-02-06 23:40 UTC, merged