feat: add `prev` caveat to `store/list` and `upload/list`
web3-storage/w3protocol pull request #423
Opened 2023-02-06 08:23 UTC by travis

Per https://github.com/web3-storage/w3ui/issues/143 we'd like to give clients a way to get the previous page of results rather than the next page.

This change introduces a `prev` caveat which, when set to true, will return the page of results preceding `cursor`.

I considered calling this `reverse` or `rev` but I think that implies that results will be returned sorted in reverse, which is not the intent.

Currently have this merging into `chore/document-paging` to make the diff clean, will retarget to main once #422 is merged.

2023-02-06 09:55 UTC, alanshaw commented
@travis if I'm understanding this correctly, this would enable you to page in either direction, but would prevent switching direction without storing some state (the cursor for the current page).

I think I had imagined this as being a change to the return value, where you'd get 2 cursors `previous` and `next` instead of one `cursor`. Then you could use that to get the previous or next page without having to store any state.

2023-02-08 12:25 UTC, alanshaw requested changes
Code changes look good but maybe we should name this parameter differently? `prev` implies there's some kind of time element here - i.e. it was previously retrieved...but that's not necessarily the case.

Maybe this is weird but what about just `pre?: boolean` or `precursor?: boolean`.

2023-02-08 18:28 UTC, gobengo commented
> 

IMO `prev` implies ordering but not necessary by type, and makes sense here too in the same way it makes sense in:
* html link rel 'prev' https://html.spec.whatwg.org/multipage/links.html#link-type-prev
  > The [prev](https://html.spec.whatwg.org/multipage/links.html#link-type-prev) keyword indicates that the document is part of a sequence, and that the link is leading to the document that is the previous logical document in the sequence.
  * which is in IANA link relation registry https://www.iana.org/assignments/link-relations/link-relations.xhtml
* also used for ordered paging (but not necessarily by time) in as2 https://www.w3.org/TR/activitystreams-vocabulary/#dfn-prev which iirc was informed by [ldp-paging](https://www.w3.org/TR/ldp-paging/#dfn-previous-page-link) doing the same

2023-02-09 11:12 UTC, alanshaw commented
@gobengo noted, thank you. Although, the things you linked to (`rel`, AS2 etc.) are _links_ sent by the _server_ to the previous document in the sequence but here we're using it as an option (a boolean) from the _client_ to enable a specific behaviour in the _server_. i.e. that we want the page of results preceeding the `cursor` we've sent. So I think this is a different enough situation to warrant a divergence, and as @travis pointed out, folks can think of `pre` as "previous" if that works better for them.

Ideally we'd have what I was [originally advocating for](https://github.com/web3-storage/w3protocol/pull/423#issuecomment-1418808379) - which _would_ be `previous` and `next`, sent by the server...but we decided against due to limitations of our tech choices 🙈.

2023-02-09 11:14 UTC, alanshaw approved these changes

2023-02-09 11:14 UTC, alanshaw commented on spec/capabilities.md
> +| `nb.pre`    | boolean                  | ❌         | If true, return previous page of results                        |
```suggestion
| `nb.pre`    | boolean                  | ❌         | If true, return the page of results preceeding the cursor |
```

2023-02-09 11:14 UTC, alanshaw commented on spec/capabilities.md
> +| `nb.pre`    | boolean                  | ❌         | If true, return previous page of results                        |
```suggestion
| `nb.pre`    | boolean                  | ❌         | If true, return the page of results preceeding the cursor |
```

2023-02-10 03:09 UTC, merged